baseURL = ""
languageCode = "en-us"
title = "Hugo Creative Theme"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Institute of Ethical Leadership"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Beyond the Bottom Line"
		subtitle   = "Enrich your professional experience and reach for excellence"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "We provide denominational leaders with an opportunity for continued professional growth and peer-to-peer networking in a collegial environment rich with content to motivate, challenge, and inspire attendees. [NASBA Policy Statements](//google.com)"
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Professional Growth"
            description = "We provide denominational leaders with an opportunity for continued professional growth"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Peer-to-Peer Networking"
			description = "Collegial environment rich with content to motivate, challenge, and inspire attendees."

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "Content that is relevant and filled with cutting edge thinking"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Grass Roots Governance"
            description = " Structure that operates independently and cooperatively with the NAD"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Resources"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "423.236.2437"
		email = "business@southern.edu.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "35.048189"
	# 	longitude = "-85.050366"
	# 	maps_api_key = ""
